config/routes.rb
FujiDaigoWakatakekai::Application.routes.draw do
  resources :uploads

  resources :posts

  root to: "pages#root"

  resources :admin, only: [:index] do
    collection do
      post :become_admin
    end
  end

  match "/:action",
    :constraints => { :action => /#{Page.all.map(&:path).join('|')}|reset/ },
    :to => 'pages',
    :as => :pages,
    :via => [:get, :post]
end

app/models/post.rb
class Post < ActiveRecord::Base
  before_save :set_draft
  before_create :set_published_at

  validates_uniqueness_of :hash_name, scope: :path, allow_nil: true, allow_blank: true

  has_many :uploads

  FORMATS = [:text, :html]
  as_enum :format, FORMATS, prefix: true

  scope :published, -> {
    where(Post.arel_table[:published_at].not_eq(nil))
  }

  paginates_per 5

  def initialize(args)
    super
    set_published_at
  end

  def link_title
    title.present? ? title : "（無題）"
  end

  def draft=(val)
    @set_draft = val.to_i != 0
  end

  def draft
    published_at == nil
  end

  def draft?
    draft
  end

  def parsed_content
    unless @parsed_content
      @parsed_content = ""
      segments = content.split /(\[\[.*?\]\])/
      segments.each do |seg|
        matched = seg.match /\[\[(.*?)(?:\((\d+),(\d+)\))?(:nolink|:link|:square)?(:thumb)?\]\]/i
        if matched && matched[1] == '__gallery__'
          uploads.order(:created_at).each do |upload|
            image = "<a href='#{upload.url}'><div class='img-cover' style='background-image: url(#{upload.thumb_url});'></div></a>"
            @parsed_content += image
          end
        elsif matched && (upload = Upload.get(matched[1]))
          size_condition = matched[2] && matched[3] ? " width='#{matched[2]}px' height='#{matched[3]}px'" : ""
          image = ''
          if matched[4] == ':square'
            image = "<a href='#{upload.url}'>■</a>"
          elsif matched[4] == ':link'
            image = "<a href='#{upload.url}'>#{upload.filename}</a>"
          else
            image_url = matched[5] == ':thumb' ? upload.thumb_url : upload.url
            image = "<img src='#{image_url}'#{size_condition}>"
            image = "<a href='#{upload.url}'>#{image}</a>" if matched[4] != ':nolink'
          end
          @parsed_content += image
        else
          @parsed_content += seg
        end
      end
    end
    @parsed_content
  end

  def processed_content
    if format_text?
      nl2br parsed_content
    else
      parsed_content.to_s.html_safe
    end
  end

  private
    def set_draft
      if @set_draft
        self.published_at = nil
      end
    end

    def set_published_at
      self.published_at ||= Time.now unless @set_draft
    end

    def nl2br(str)
      return ''.html_safe if str.blank?
      str = str.split(/\r\n|\n\r|\r|\n/o).map {|line| line }.join('<br>')
      str.html_safe
    end
end

app/controllers/posts_controller.rb
class PostsController < ApplicationController
  before_action :authenticate_admin
  before_action :set_post, only: [:show, :edit, :update, :destroy]

  # GET /posts
  # GET /posts.json
  def index
    @posts = Post.where(published_at: nil) + Post.published.order(:published_at).reverse_order
  end

  # GET /posts/1
  # GET /posts/1.json
  def show
  end

  # GET /posts/new
  def new
    @post = Post.new(path: params[:path])
  end

  # GET /posts/1/edit
  def edit
  end

  # POST /posts
  # POST /posts.json
  def create
    @post = Post.new(post_params)

    respond_to do |format|
      if @post.save
        format.html { redirect_to @post.draft? ? post_path(@post) : pages_path(@post.path), notice: '正常に新規投稿が作成されました' }
        format.json { render action: 'show', status: :created, location: @post }
      else
        format.html { render action: 'new' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /posts/1
  # PATCH/PUT /posts/1.json
  def update
    respond_to do |format|
      if @post.update(post_params)
        format.html { redirect_to @post.draft? ? post_path(@post) : pages_path(@post.path), notice: '正常に投稿が更新されました' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @post.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /posts/1
  # DELETE /posts/1.json
  def destroy
    @post.destroy
    respond_to do |format|
      format.html { redirect_to posts_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_post
      @post = Post.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def post_params
      params.require(:post).permit(:path, :title, :content, :published_at, :draft, :format_cd)
    end
end

app/views/posts/_form.html.erb
<%= form_for(@post) do |f| %>
  <% if @post.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@post.errors.count, "error") %> prohibited this post from being saved:</h2>

      <ul>
      <% @post.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :path, "対象ページ" %><br>
    <%= f.select :path, options_from_collection_for_select(Page.all, :path, :title, @post.path), style: "width: 150px;" %>
  </div>
  <div class="field">
    <%= f.label :title, "タイトル" %><br>
    <%= f.text_field :title, style: "width: 500px;" %>
  </div>
  <div class="field">
    <%= f.label :content, "内容" %><br>
    <%= f.text_area :content, style: "width: 500px; height: 250px;" %>
  </div>

  <%= link_to "画像の追加", "#upload-modal", class: "ui-show-modal" %>
  <%= render "uploads", post: @post %>

  <div class="field">
    <%= f.check_box :format_cd %>
    <%= f.label :format_cd, "HTML形式で入力" %><br>
  </div>
  <div class="field", id="published_at_field">
    <%= f.label :published_at, "投稿日時(投稿順に関係)" %><br>
    <%= f.datetime_select :published_at, use_month_numbers: true %>
  </div>

  <div class="field">
    <%= f.check_box :draft %>
    <%= f.label :draft, "下書きとして保存" %><br>
  </div>
  <div class="actions">
    <%= f.submit "反映" %>
  </div>
<% end %>

<%= render_dialog "upload", id: "upload-modal", scroll: true, title: "画像の追加", upload: Upload.where(post_id: @post).new %>

<% content_for :extra_scripts do %>
  <%= javascript_tag do %>
    $(function() {
      var check_draft = function() {
        if ($('#post_draft').prop('checked')) {
          $('#published_at_field').hide();
        } else {
          $('#published_at_field').show();
        }
      };
      check_draft();
      $('#post_draft').on('change', check_draft);
    });
  <% end %>
<% end %>

app/views/posts/_uploads.html.erb
<div class="field edit-gallery">
  関連付けられた画像<br>
  <% if post.uploads.present? %>
    <% post.uploads.each do |upload| %>
      <a href='<%= upload_path(upload) %>' target='_blank'>
        <div class='img-cover' style='background-image: url(<%= upload.thumb_url %>);'></div>
      </a>
    <% end %>
  <% else %>
    <p class="no-content">
      関連画像はありません
    </p>
  <% end %>
</div>

app/views/posts/edit.html.erb
<div class="column">
<h2 class="sub-head">投稿編集</h2>

<div class="content">
<%= render 'form' %>
</div>

<div class="clearfix" style="margin: -50px 5px 20px;">
  <%= button_to '削除', @post, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "right" %>
</div>

<%= link_to '一覧へ', posts_path %>

</div>

app/views/posts/index.html.erb
<%= link_to '新規投稿作成', new_post_path %>

<div class="column">
<h2 class="sub-head">投稿管理 - 一覧</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>対象URL</th>
      <th>タイトル</th>
      <th>投稿日</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @posts.each do |post| %>
      <tr>
        <td><%= post.path %></td>
        <td><%= link_to post.link_title, edit_post_path(post) %></td>
        <td><%= post.published_at ? l(post.published_at) : '下書き' %></td>
        <td><%= button_to '削除', post, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

app/views/posts/new.html.erb
<div class="column">
<h2 class="sub-head">新規投稿作成</h2>

<div class="content">
<%= render 'form' %>
</div>
<%= link_to '一覧へ', posts_path %>

</div>

app/views/posts/show.html.erb
このページは管理者のみ閲覧可能な個々の投稿のページです。
<% if Page.find(@post.path).present? %>
  <br>
  「<%= link_to Page.find(@post.path).title.gsub('<br>',''), pages_path(@post.path) %>」へ行く
<% end %>

<%= render partial: 'post', object: @post %>

<%= link_to '一覧に戻る', posts_path %>