config/routes.rb
FujiDaigoWakatakekai::Application.routes.draw do
  resources :uploads

  resources :posts

  root to: "pages#root"

  resources :admin, only: [:index] do
    collection do
      post :become_admin
    end
  end

  match "/:action",
    :constraints => { :action => /#{Page.all.map(&:path).join('|')}|reset/ },
    :to => 'pages',
    :as => :pages,
    :via => [:get, :post]
end

app/models/upload.rb
class Upload < ActiveRecord::Base
  belongs_to :post
  mount_uploader :file, FileUploader
  before_save :set_info

  validates_presence_of :file

  def image_type?
    file && file.content_type.start_with?('image')
  end

  def filename
    file ? file.file.filename : nil
  end

  def url
    file ? file.url : nil
  end

  def thumb_url
    file ? (file.thumb.present? ? file.thumb.url : file.url) : nil
  end

  def self.get(name, category: nil)
    scope = Upload.order(:id)
    res = nil
    res = scope.where(category: category, name: name).last if category.present?
    res ||= scope.where(name: name).last
  end

  def self.get_url(name, category: nil)
    get(name, category: category).try(:url)
  end

  def set_info
    self.name = filename if name.blank?
    self.category = post.path if category.blank? && post.present?
  end
end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController
  before_action :authenticate_admin, except: [:show]
  before_action :set_upload, only: [:show, :edit, :update, :destroy]

  # GET /uploads
  # GET /uploads.json
  def index
    @uploads = Upload.all
  end

  # GET /uploads/1
  # GET /uploads/1.json
  def show
  end

  # GET /uploads/new
  def new
    @upload = Upload.new
  end

  # GET /uploads/1/edit
  def edit
  end

  # POST /uploads
  # POST /uploads.json
  def create
    @upload = Upload.new(upload_params)

    respond_to do |format|
      if @upload.save
        format.html { redirect_to @upload, notice: 'ファイルが正常にアップロードされました' }
        format.json { render action: 'show', status: :created, location: @upload }
        format.js
      else
        format.html { render action: 'new' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
        format.js
      end
    end
  end

  # PATCH/PUT /uploads/1
  # PATCH/PUT /uploads/1.json
  def update
    respond_to do |format|
      if @upload.update(upload_params)
        format.html { redirect_to @upload, notice: 'ファイルが正常に更新されました' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @upload.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /uploads/1
  # DELETE /uploads/1.json
  def destroy
    @upload.destroy
    respond_to do |format|
      format.html { redirect_to uploads_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_upload
      @upload = Upload.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def upload_params
      params.require(:upload).permit(:post_id, :category, :name, :file)
    end
end

app/views/uploads/_form.html.erb
<%= form_for(@upload) do |f| %>
  <% if @upload.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@upload.errors.count, "error") %> prohibited this upload from being saved:</h2>

      <ul>
      <% @upload.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.hidden_field :post_id %>
  <% if @upload.post.present? %>
    <div class="field">
      以下のページから投稿<br>
      <%= link_to @upload.post.title, post_path(@upload.post) %>
    </div>
  <% end %>
  <!--
  <div class="field">
    <%= f.label :category, "カテゴリ" %><br>
    <%= f.text_field :category %>
  </div>
  -->
  <% unless @upload.new_record? %>
    <div class="field">
      <%= f.label :name, "投稿からの参照名" %><br>
      <%= f.text_field :name %>
    </div>
  <% end %>
  <div class="field">
    <% if @upload.url.present? %>
      <% if @upload.image_type? %>
        <%= link_to @upload.url, target: "_blank", id: "thumb-image" do %>
          <%= image_tag @upload.thumb_url %>
        <% end %>
      <% else %>
        <%= link_to @upload.filename, @upload.url, target: "_blank" %>
      <% end %>
      <br>
      画像の変更：
    <% end %>
    <%= f.file_field :file %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

<% content_for :extra_scripts do %>
  <%= javascript_tag do %>
    $(function() {
      $(document).on('change', '#upload_file', function() {
        $('#thumb-image').hide();
      });
    });
  <% end %>
<% end %>

app/views/uploads/edit.html.erb
<div class="column">
<h2 class="sub-head">アップロードファイルの更新</h2>

<div class="content">
<%= render 'form' %>
</div>

<div class="clearfix" style="margin: -50px 5px 20px;">
  <%= button_to '削除', @upload, method: :delete, data: { confirm: '本当に削除してよろしいですか？' }, class: "right" %>
</div>

<%= link_to '一覧へ', uploads_path %>

</div>

app/views/uploads/index.html.erb
<div class="column">
<h2 class="sub-head">アップロード一覧</h2>

<table class="table table-striped">
  <thead>
    <tr>
      <th>カテゴリ</th>
      <th>紐付いている投稿</th>
      <th>ファイル名</th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @uploads.each do |upload| %>
      <tr>
        <td><%= upload.category %></td>
        <td><%= upload.post_id.present? ? link_to(upload.post.title, post_url(upload.post)) : "-" %></td>
        <td><%= link_to upload.name, edit_upload_path(upload) %></td>
        <td><%= button_to '削除', upload, method: :delete, data: { confirm: '本当に削除してよろしいですか？' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>

<%= link_to '新規アップロード', new_upload_path %>

app/views/uploads/new.html.erb
<div class="column">
<h2 class="sub-head">新規ファイルアップロード</h2>

<div class="content">
<%= render 'form' %>
</div>
<%= link_to '一覧へ', uploads_path %>

</div>

app/views/uploads/show.html.erb
<div class="column">
<div class="sub-head clearfix">
  <h2 class="left"><%= @upload.name %></h2>
  <% if cookies[:role] == 'fdw' || params[:controller] == 'uploads' %>
    <%= link_to "編集", edit_upload_path(@upload), class: "right" %>
  <% end %>
</div>
<div class="content">
  <%= link_to @upload.url do %>
    <% if @upload.image_type? %>
      <%= image_tag @upload.url, alt: @upload.name %>
    <% else %>
      ダウンロード
    <% end %>
  <% end %>
</div>
</div>

<%= link_to '一覧に戻る', uploads_path %>